using System;
using System.Collections.Generic;

namespace GraphQL.Models
{
    public partial class RcmTaxInvoiceHeader
    {
        public RcmTaxInvoiceHeader()
        {
            RcmTaxInvoiceDetails = new HashSet<RcmTaxInvoiceDetail>();
            RcmTaxInvoiceServiceDetails = new HashSet<RcmTaxInvoiceServiceDetail>();
        }

        public long TaxInvoiceNo { get; set; }
        public int OrganizationId { get; set; }
        public string? EinvoiceNo { get; set; }
        public int? FacilityId { get; set; }
        public int PayerId { get; set; }
        public int? PayerIdTpa { get; set; }
        public DateTime InvoiceDate { get; set; }
        public DateTime TransFromDate { get; set; }
        public DateTime TransToDate { get; set; }
        public byte Status { get; set; }
        public byte? TaxInvoiceSourceType { get; set; }
        public bool IsAutoGenerated { get; set; }
        public bool IsPostedToZatca { get; set; }
        public DateTime? PostedDate { get; set; }
        public string? PostingRemarks { get; set; }
        public int CreatedBy { get; set; }
        public DateTime CreatedOn { get; set; }
        public int? UpdatedBy { get; set; }
        public DateTime? UpdatedOn { get; set; }
        public int? VerifiedBy { get; set; }
        public DateTime? VerifiedOn { get; set; }
        public int? ApprovedBy { get; set; }
        public DateTime? ApprovedOn { get; set; }
        public byte[] RowVer { get; set; } = null!;
        public string? Uuid { get; set; }
        public bool IsMoh { get; set; }
        public string? InvoiceQrCode { get; set; }

        public virtual ICollection<RcmTaxInvoiceDetail> RcmTaxInvoiceDetails { get; set; }
        public virtual ICollection<RcmTaxInvoiceServiceDetail> RcmTaxInvoiceServiceDetails { get; set; }
    }
}
